// THIS IS . PROGRAM TO READ TWO NOS. AND PERFORM SPECIFIC TASK (USING ARITHMETIC 
// OPERATOR)AND THIS PERFORM USING SWITCH-CASE.(CASE IN CHAR FORM).

#include <stdio.h>
int main() {
    
    return 0;
}
